name: ztdlbootcamp
channels:
- defaults
dependencies:
- python=3.6
- bz2file==0.98
- cython==0.28.*
- flask==1.0.*
- gensim==3.4.*
- h5py==2.8.*
- jupyter==1.0.*
- matplotlib==3.0.*
- numpy==1.14.5
- pandas==0.23.*
- pillow==5.3.*
- pip==10.0.*
- pytest==3.8.*
- setuptools==39.1.0
- scikit-learn==0.20.*
- scipy==1.1.*
- seaborn==0.9.*
- twisted==17.5.*
- tensorflow==1.10.*
- pip:
  - PyHamcrest==1.9.*
  - keras==2.2.*
  - jupyter_contrib_nbextensions==0.5.*
  - tensorflow-serving-api==1.10.*
  - wandb==0.6.*
